#!/bin/bash

for VERSION in 5.14.4 5.16.3 5.18.4 5.20.3 5.22.4 5.24.4 5.26.3 5.28.3 5.30.3 5.32.1 5.34.1 5.36.0 ; do
   echo "processing $VERSION"
   MINOR=$(echo "$VERSION" | cut -d . -f3)
   MAJOR="$(echo "$VERSION" | cut -d . -f2)"
   ATVER="$(echo "$VERSION" | cut -d . -f1)$(echo "$VERSION" | cut -d . -f2)"
   if [ $MAJOR -gt 20 ]
   then
       SUFFIX="xz"
   else
       SUFFIX="bz2"
   fi
   if [ $MAJOR -lt 32 ] && [ $MAJOR -ge 24 ]
   then
       PATCHDATA="  patch :DATA"
   else
       PATCHDATA=""
   fi
   URL="https://www.cpan.org/src/5.0/perl-${VERSION}.tar.${SUFFIX}"
   SHA256=$(curl -s "$URL" | sha256sum | cut -d ' ' -f1)
   sed  "s/@@ATVER@@/${ATVER}/;s/@@VERSION@@/${VERSION}/;s/@@SUFFIX@@/${SUFFIX}/;s/@@SHA256@@/${SHA256}/;s/@@PATCHDATA@@/${PATCHDATA}/" < perl-templaterb > Formula/perl@5.${MAJOR}.rb
   if [ ! -z "$PATCHDATA" ]
   then
      if [ $MAJOR -eq 24 ]
      then
          sed -n '/^@@ -342/q;p' perl-patch >> Formula/perl@5.${MAJOR}.rb
      else
          cat perl-patch >> Formula/perl@5.${MAJOR}.rb
      fi
   fi
done
